# Generated by Django 2.0.5 on 2018-07-14 12:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BiomarkersLookUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_column='Name', max_length=255, null=True)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=255, null=True)),
                ('city', models.CharField(blank=True, db_column='City', max_length=255, null=True)),
                ('state', models.CharField(blank=True, db_column='State', max_length=50, null=True)),
                ('zip', models.CharField(blank=True, db_column='Zip', max_length=20, null=True)),
                ('phone', models.CharField(blank=True, db_column='Phone', max_length=20, null=True)),
                ('field_colontown_patients', models.CharField(blank=True, db_column='# ColonTown Patients', max_length=100, null=True)),
                ('guestimated_of_hai_implants_per_year', models.CharField(blank=True, db_column='Guestimated # of HAI Implants per year', max_length=255, null=True)),
                ('url', models.CharField(blank=True, db_column='URL', max_length=255, null=True)),
                ('ct_contacts', models.CharField(blank=True, db_column='CT Contacts', max_length=255, null=True)),
                ('longitude', models.CharField(blank=True, db_column='Longitude', max_length=20, null=True)),
                ('latitude', models.CharField(blank=True, db_column='Latitude', max_length=20, null=True)),
            ],
            options={
                'db_table': 'hospital',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dx_date', models.DateField(blank=True, null=True)),
                ('last_treatment_date', models.DateField(blank=True, null=True)),
                ('ned', models.CharField(choices=[('YES', 'Yep'), ('NO', 'Nope')], default='YES', max_length=20)),
                ('stage_now', models.CharField(choices=[('1', 'I'), ('2', 'II'), ('3', 'III'), ('3', 'III A'), ('3', 'III B'), ('3', 'III C'), ('4', 'IV')], default='1', max_length=20)),
                ('stage_at_dx', models.CharField(choices=[('1', 'I'), ('2', 'II'), ('3', 'III'), ('3', 'III A'), ('3', 'III B'), ('3', 'III C'), ('4', 'IV')], default='1', max_length=20)),
                ('msi_status', models.CharField(choices=[('MSS', 'MSS'), ('MSIH', 'MSI-H')], default='MSS', max_length=20)),
                ('biomarkers', models.ManyToManyField(to='haipumpfinder.BiomarkersLookUp')),
                ('user', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'patient',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=255)),
                ('trial_id', models.CharField(max_length=100)),
                ('dose_schedule', models.TextField(max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('last_treatment_date', models.DateField(blank=True, null=True)),
                ('response', models.TextField(max_length=255)),
                ('treatment_notes', models.TextField(max_length=255)),
                ('side_effect', models.TextField(max_length=255)),
                ('user', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('start_date',),
            },
        ),
    ]
