# Generated by Django 2.0.2 on 2018-04-16 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_column='Name', max_length=255, null=True)),
                ('address', models.CharField(blank=True, db_column='Address', max_length=255, null=True)),
                ('city', models.CharField(blank=True, db_column='City', max_length=255, null=True)),
                ('state', models.CharField(blank=True, db_column='State', max_length=50, null=True)),
                ('zip', models.CharField(blank=True, db_column='Zip', max_length=20, null=True)),
                ('phone', models.CharField(blank=True, db_column='Phone', max_length=20, null=True)),
                ('field_colontown_patients', models.CharField(blank=True, db_column='# ColonTown Patients', max_length=100, null=True)),
                ('guestimated_of_hai_implants_per_year', models.CharField(blank=True, db_column='Guestimated # of HAI Implants per year', max_length=255, null=True)),
                ('url', models.CharField(blank=True, db_column='URL', max_length=255, null=True)),
                ('ct_contacts', models.CharField(blank=True, db_column='CT Contacts', max_length=255, null=True)),
                ('longitude', models.CharField(blank=True, db_column='Longitude', max_length=20, null=True)),
                ('latitude', models.CharField(blank=True, db_column='Latitude', max_length=20, null=True)),
            ],
            options={
                'db_table': 'hospital',
                'managed': True,
            },
        ),
    ]
