# Generated by Django 2.0.5 on 2018-08-07 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haipumpfinder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='treatments',
            field=models.ManyToManyField(to='haipumpfinder.Treatment'),
        ),
    ]
