# Generated by Django 2.0.5 on 2018-08-08 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('haipumpfinder', '0002_patient_treatments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='treatments',
        ),
        migrations.RemoveField(
            model_name='treatment',
            name='user',
        ),
        migrations.AddField(
            model_name='treatment',
            name='patient',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='haipumpfinder.Patient'),
        ),
        migrations.AlterModelTable(
            name='treatment',
            table='treatment',
        ),
    ]
