# Generated by Django 2.0.5 on 2018-05-27 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('haipumpfinder', '0007_profile_msi_status'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table=None,
        ),
    ]
