# Generated by Django 2.0.5 on 2018-05-27 14:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('haipumpfinder', '0008_auto_20180527_0828'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='profile',
            table='profile',
        ),
    ]
