# Generated by Django 2.0.5 on 2018-05-27 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('haipumpfinder', '0009_auto_20180527_0829'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='msi_status',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='stage_at_dx',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='stage_now',
        ),
    ]
