# Generated by Django 2.0.5 on 2018-05-27 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haipumpfinder', '0015_auto_20180527_0857'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='msi_status',
            field=models.CharField(choices=[('MSS', 'MSS'), ('MSIH', 'MSI-H')], default='MSS', max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='stage_at_dx',
            field=models.CharField(choices=[('1', 'I'), ('2', 'II'), ('3', 'III'), ('4', 'IV')], default='1', max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='stage_now',
            field=models.CharField(choices=[('1', 'I'), ('2', 'II'), ('3', 'III'), ('4', 'IV')], default='1', max_length=20),
        ),
    ]
