# Generated by Django 2.0.5 on 2018-05-27 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('haipumpfinder', '0017_patient_ned'),
    ]

    operations = [
        migrations.CreateModel(
            name='BiomarkersLookUp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AlterField(
            model_name='patient',
            name='stage_at_dx',
            field=models.CharField(choices=[('1', 'I'), ('2', 'II'), ('3', 'III'), ('3', 'III A'), ('3', 'III B'), ('3', 'III C'), ('4', 'IV')], default='1', max_length=20),
        ),
        migrations.AlterField(
            model_name='patient',
            name='stage_now',
            field=models.CharField(choices=[('1', 'I'), ('2', 'II'), ('3', 'III'), ('3', 'III A'), ('3', 'III B'), ('3', 'III C'), ('4', 'IV')], default='1', max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='biomarkers',
            field=models.ManyToManyField(to='haipumpfinder.BiomarkersLookUp'),
        ),
    ]
