# Generated by Django 2.0.5 on 2018-05-28 00:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('haipumpfinder', '0019_auto_20180527_1829'),
    ]

    operations = [
        migrations.CreateModel(
            name='Treatment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desciption', models.TextField(max_length=255)),
                ('trial_id', models.CharField(max_length=100)),
                ('dose_schedule', models.TextField(max_length=255)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('last_treatment_date', models.DateField(blank=True, null=True)),
                ('response', models.TextField(max_length=255)),
                ('treatment_notes', models.TextField(max_length=255)),
                ('side_effect', models.TextField(max_length=255)),
                ('user', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('start_date',),
            },
        ),
    ]
